services:
  - type: web
    name: gram-panchayat
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: gunicorn -w 1 --threads 10 main:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
